version: '3'
services:
  web:
    image: "rplace"
    ports:
      - 80:80
    networks:
      - rplace
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    networks: 
      - rplace
networks:
  rplace:
    driver: overlay